### ISSUE TITLE
Mirror blocks to treat Common Cause Failures in Fault Trees

### ISSUE THREAD

**Issue by wilsonpaulo** [jto888/FaultTree#22]
When treating Common Cause Failures (CCF) in Fault Trees using addDuplicate() function it will duplicate the block and place it on desired branch, but, will compute the Probability of Failure (Pf) as it was a another input event. This way, a CCF will contribute the number of times it was duplicated with the same Pf instead of contributing only once for the entire tree.
If we take a look to [this link](https://www.weibull.com/hotwire/issue54/relbasics54.htm), it explains that mirrored blocks will produce different probability of failure than same failure placed several times.

**Comment by jto888** [comment]
At the time of this comment I had directed Wilson Paulo to use SCRAM in order to access the probability calculation he requested. As of FaultTree v 0.99 calculations can now be requested with use.bdd=TRUE to assure exact probability calculations with multiply occurring events.
