### ISSUE TITLE
Separate data and representation

### ISSUE THREAD

**Issue by rakhimov** [jto888/FaultTree#8]
The provided language combines events and their graphical representation.
This adds unnecessary complexity. What if I don't need the graphs?
It is easy to mess up as well.
I think graphs could be handled by point-&-click front end better than hard-coding.
This would also remove lots of noise from the code.

**Comment by jto888** [comment]
Not sure this is an issue. Yes, some events may be graphically depicted in a single chain under an OR gate. This required a distinction between Graphical Parent and Calculation Parent. This option is set while adding the event, but not mandatory. This is the only occasion in which there is a "mixing" of events with their graphical representation.
The tree is built as a data table (actually dataframe in R). It is not necessary to prepare or look at the graphical representation, but most find it satisfying.
A point and click front end would be more complex than I think you expect. Noisy also. Such a front end would have to build and modify the defining script, else graphic modifications changing the data table only would render the original script out of data and of no value.
The script is very useful for stochastic analysis.
